### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SlyBlack** [Aelto/W3_RandomEncounters_Tweaks#63]
Hi, i installed the mod, but the game wont open, i've tried to merge, but the script merger says there's nothing, so i'm trying here... sorry for the inconvenience...

Error [modrandomencountersreworked]local\rer_scripts.min.ws(13873): Unknown base class 'SU_InteractionEventListener'
Error [modrandomencountersreworked]local\rer_scripts.min.ws(14646): Unknown base class 'SU_ErrandInjector'
Error [modrandomencountersreworked]local\rer_scripts.min.ws(21775): Unknown base class 'SU_PredicateInterfaceRemovePin'

here's the code

**Comment by Aelto** [comment]
Hi, if you download the mod from the [releases](https://github.com/Aelto/W3_RandomEncounters_Tweaks/releases) here or on Nexusmods (it's basically just a mirror of the releases) you'll see the mod comes with the sharedutils mods. You need to install them as well, and then you will need to run the script-merger.
